CREATE DATABASE IF NOT EXISTS crypto;

USE crypto;

DROP table if EXISTS cryptoseelist;
DROP TABLE IF EXISTS cryptolist;
DROP TABLE IF EXISTS crypto;

CREATE TABLE CRYPTO (	
	SYMBOL CHAR(7) NOT NULL UNIQUE,
    BLOCKCHAIN_ID ENUM ('PUB', 'PRIV', 'FED') NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CURRENTPRICE DECIMAL (8,3) NOT NULL,
	PRIMARY KEY (SYMBOL)
);

CREATE TABLE CRYPTOLIST (
	LIST_PK INT(11) NOT NULL AUTO_INCREMENT UNIQUE,
	NAME VARCHAR(12) NOT NULL,	
				
	PRIMARY KEY (CRYPTOLIST_PK)
    );

CREATE TABLE CRYPTOSEELIST (
	CRYPTOSEELIST_PK INT(12) NOT NULL AUTO_INCREMENT,
	CRYPTOLIST_FK INT(12) NOT NULL,
	CRYPTO_SYMBOL CHAR(7),
	PRIMARY KEY (CRYPTOSEELIST_PK),
	FOREIGN KEY (CRYPTOLIST_FK)
		REFERENCES CRYPTOLIST (CRYPTOLIST_PK),
	FOREIGN KEY (CRYPTO_SYMBOL)
		REFERENCES CRYPTO (SYMBOL)
);